### ISSUE TITLE
See blank screen after install and npm start

### ISSUE THREAD

**Issue by dijimon** [workco/marvin#69]
Why I don't see any home page or smth. instead of blank screen. 
There are some components in source code and probably they should be displayed when I go to http://localhost:8081/

**Comment by Stanko** [comment]
Hello @dijimon,
Please when you open an issue, try to give more information. Browser, os and node version can help. Copying the whole error stack too. I can't help you when I don't know what the problem is.

Marvin by default uses port `8080` so you have something running on that port if webpack switched to `8081`. So other process might be blocking it. This is a wild guess, as you haven't provided any info.

Cheers!

**Comment by dijimon** [comment]
OS: macOS 10.13.1
Browser: Chrome version 63.0.3239.132 (Official Build) (64-bit)
NodeJS: v8.6.0

npm start
Project is running at http://0.0.0.0:8083/
webpack output is served from /
Content not from webpack is served from /Users/.../.../source
404s will fallback to /index.html

ERROR in ./source/js/client.js
Module build failed: SyntaxError: Unexpected token (22:2)

 21 | renderMethod(
> 22 |   <AppContainer>
     |   ^
  23 |     <Provider store={ store }>

@ multi (webpack)-dev-server/client?http://0.0.0.0:8083 webpack/hot/dev-server babel-polyfill ./source/js/client.js
webpack: Failed to compile.

**Comment by Stanko** [comment]
You probably downloaded a zip, and when unzipped, you haven't copied hidden files including `.babelrc` and other config files. Without babel configuration webpack can't handle JSX files.

**Comment by dijimon** [comment]
Thanks, you are right
